name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [17, 19]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - uses: actions/checkout@v2
      - run: ./gradlew check build --stacktrace --parallel
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
